### ISSUE TITLE
Limitations / nested nodes order

### ISSUE THREAD

**Issue by dy** [WebReflection/domdiff#17]
Is there any info on limitations of `parentNode`, `currentNodes`, `futureNodes`?
Eg. can `currentNodes` be not `childNodes` of `parentNode`, but some arbitrary set of nodes? Can they belong to different parents?
Can `currentNodes` include one another? Eg.
```js
  let a = document.createElement('a')
  a.innerHTML = `
    <x><y></y></x>
    <z></z>
  `

  let x = a.querySelector('x')
  let y = a.querySelector('y')
  let z = a.querySelector('z')

  domdiff(a, [x,y,z], [y,z,x])
  a.innerHTML === `
    <z></z>
  <x><y></y></x>
  `
```
What's the logic behind this result? Is that expected? Another example:
```js
a.innerHTML = `<x><y></y></x><z></z>`

  let x = a.querySelector('x')
  let y = a.querySelector('y')
  let z = a.querySelector('z')

  domdiff(a, [x,y], [y,z])

  console.log(a.innerHTML)  === `<z></z>` // y is missing
```
If `currentNodes` can be only `childNodes` of some parent - why API requires `parentNode` as first argument?

Is there any sense to add some explanation to these questions in the readme?

Thanks!

**Comment by WebReflection** [comment]
the `domdiff` utility **must own** the handling of the element content, and nodes must be those expected, meaning you cannot pass arbitrary nodes as list of current nodes, and nodes are handled only on the first level.

I suggest you don't use this library right away, but use [lighterhtml](https://github.com/WebReflection/lighterhtml#readme), [hyperHTML](https://github.com/WebReflection/hyperHTML#readme), or [heresy](https://github.com/WebReflection/heresy#readme) instead, as it's obvious there how this library works, which is always by owning the nodes it populates, update, and change.

_TL;DR_ no, you can't mess up with nodes, either one is fully handled by domdiff, or you are causing issues that wouldn't be there otherwise.
