### ISSUE TITLE
[Question] How to diff to different elements 

### ISSUE THREAD

**Issue by strowbeary** [WebReflection/domdiff#19]
Hello,
I would like to use domdiff for a project and i have a function call tree that give me a single node as return value. Each time i call this function tree I get a new node.
How can I diff those two nodes with domdiff (or is it even possible in my case) ?

Thank you for your help !

**Comment by WebReflection** [comment]
the diff is between same list with variants, or different lists.

if every time you call that function it creates new nodes, everything is different, 'cause each node could have listeners attached, as example, so that there's really nothing domdiff can do, if not replace the previous one with the new node.

accordingly, this is likely not the library you are looking for, as it deals with identities and equality, and if all nodes are always different, this library is pointless.

As summary, this function you call, should never crate new nodes per each invocation.
