### ISSUE TITLE
[Question] what is the difference between -0 and 0?

### ISSUE THREAD

**Issue by prof7bit** [WebReflection/domdiff#22]
I am referring to the explanation of the callback function in the readme.

**Comment by WebReflection** [comment]
Does the readme answers?
https://github.com/WebReflection/domdiff#a-node-generic-info--node-callback-for-complex-data

**Comment by prof7bit** [comment]
Not really. What is the rationale of encoding 2 different states with values that lie so close to each other that they are almost indistinguishable from each other without resorting to esoteric hacks like 1/n to see the difference at all? It feels wrong to me.

Maybe I am overreacting because I am coming from a C and Pascal background, relying on the sign of a floating point zero remaining intact under all circumstances (an implementation detail of the underlying floating point implementation [on every hardware?]) and using that to communicate information seems like a bizarre idea and very fragile to someone like me who was used to use integers and/or explicit bits for most of his life.

**Comment by WebReflection** [comment]
> esoteric hacks like 1/n to see the difference at all?

it branches 2 main cases:
  * removal or after (no node, after node, hence `item[item.length - 1]` needed)
  * insert or before (new node, before node, hence no last item needed)

Any different combination would be equivalent without branching these two use cases.

An operation as `(1/i) < 0` is just math, not really an *esoteric hack*, as in JS `-0` is not `0`, and a switch case would be just more verbose.

This *esoteric hack* has been working for years, in *uhtml* too, and since 2017 in *hyperHTML*: it's pretty damn fast too!

> Maybe I am overreacting because I am coming from a C and Pascal background

Not my intent to hurt anyone there, but maybe you learned JS has this distinction between `0` and `-0`, so that we're all good and we can, hopefully, move on.

**Comment by mindplay-dk** [comment]
It seems more like you're relying on an implementation detail of IEEE numeric encoding than anything else - I realize it's technically part of the specification, but it really seems more like an artifact than something with a designated, useful or meaningful purpose? Using a bit for the sign probably made it easier to implement some microprograms at the CPU level.

The fact that strict equality comparison `0 === -0` evaluates as `true` seems to suggest these values weren't even *meant* to be compared - that fact alone makes this confusing enough that I would never rely on this unfortunate detail.

In ordinary arithmetic, the number 0 does not have a sign - so expecting `1/-0` to equal `-Infinity` isn't intuitive either.

In 20-something years of JS, it's the first time I've ever seen anyone rely on this "feature".

Really confusing. 😕

**Comment by WebReflection** [comment]
> The fact that strict equality comparison 0 === -0 evaluates as true seems to suggest ...

That it was an early mistake that for backward compatibility reasons couldn't change, and it got fixed via `Object.is` because people not aware of possible negative zero that leads to negative infinite too are dealing with a footgun that will hurt them sooner or later.

So, the best way to deal with numbers and be sure about their values is `Object.is`:

```js
Object.is(0, -0); // false
```

Because with the same argument, `NaN === NaN` is always false, and `NaN` is a reality in JS.

> In 20-something years of JS, it's the first time I've ever seen anyone rely on this "feature".

I think I've seen this before and used after thinking that was actually neat to simplify dual branches: +0, 1 vs -0, -1

> Really confusing.

I use this since years in all my diffing libraries and there is an explanation of what each value means, plus code example, plus me explaining this in here.

This feature will never change in JS because it'd break the Web if it does, it's part of IEEE which is a standard, so I don't share concerns but I don't understand why you don't wrap it as you like, with your convention, in a way that boils down to the range -1, -0, +0, +1 ... so that in your libarry nobody is confused ... 'cause to me this works already very well and, on top of that, it's pretty damn fast.

It's not elegant, if you like, but if it works and it costs zero parsing, I also think is the right "*feature*" for the job.

In few words, I am not changing this as it will give me concretely zero advantages plus I need to rewrite code and documentation and break others that just read the values and moved forward (riot JS to name one).
