### ISSUE TITLE
Use isEqualNode instead of ===

### ISSUE THREAD

**Issue by vixalien** [WebReflection/domdiff#23]
You can use `isEqualNode` to check if the nodes are equal instead of using `===`.

Example:

```js
a = document.createElement("title");
b = document.createElement("title");
a.isEqualNode(b); // returns true
a.innerText = "Hello";
a.isEqualNode(b); // returns false
b.innerText = "Hello";
a.isEqualNode(b); // returns true
b.isEqualNode(a); // returns true
```

Reference: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode)

**Comment by WebReflection** [comment]
whenever you'd like to understand what this library does and *why* `===` is the only way, unless you suggested `Object.is`, I'll be happy to help you understanding.

**Comment by vixalien** [comment]
Can you explain why `===` is the only way? And why is `Object.is` a better alternative? I came here from `udomdiff`.

Btw how hard do you think will be for domdiff to support deep (not shallow) diffing?? or can you get the code returned integer `-1` `1` or etc to further update the changed tree path.

**Comment by WebReflection** [comment]
nodes **must** be equal by identity, not by similarities ... the same node cannot exists in two different containers, two "*equal*" nodes can, and that's not diffing, that's something else ...

u/domdiff doesn't need to support deep diffing, because if the container is the same, their content will be reflected live, there's nothing to diff internally, it's the container that matters, everything else is how the DOM works already.

I hope this answers. If not, please provide an example of what are you trying to do, or trying to solve, 'cause two out of two questions you asked suggest you are not using this library in the way it's meant to be used ... have you tried **[uhtml](https://github.com/WebReflection/uhtml#readme)** instead? it abstracts away everything for you already

**Comment by vixalien** [comment]
I wanted to support instant SPA-style navigation on my site. The general idea is:

1. Load the content of the new URL
2. Look for the changed bits
3. If a script was added, add it to the scripts which will be executed.
4. After all diffing, executed new or changed scripts.

The problem is that `domdiff` immediately say that `html` and `body` were removed, then added. I was hoping it to say that they were changed, so that I could diff the elements which have changed even further (provided they have children) and go on until all scripts all discovered and everything patched.

**Comment by WebReflection** [comment]
this MR wouldn't solve any of that, for what I can tell, and hydration needs to be done through `html.for` keyed renders, in place, per each place/container you need.

**Comment by vixalien** [comment]
Could you explain a little more on how hydration should be done?
